package(default_visibility = ["//visibility:public"])

# Creative Commons Attribution 4.0 International (CC BY 4.0)
# for all the data files generated by the PhonClassCounts project.
licenses(["restricted"])

exports_files(glob(["input/*"]))

py_library(
    name = "phon_class_counts_data",
    data = glob(["input/*"]),
)