package(default_visibility = ["//visibility:public"])

# Creative Commons Attribution 4.0 International (CC BY 4.0)
# for all the data files generated by the PhonClassCounts project.
licenses(["restricted"])  # mix of GPL 3, CC BY-SA 3 and CC BY 4

exports_files(glob(["input/*"]))

genrule(
    name = "dummy_init_py",
    outs = ["__init__.py"],
    cmd = "touch $@",
)

py_library(
    name = "phon_class_counts_data",
    srcs = [":dummy_init_py"],
    data = glob(["input/*"]),
)
