sh_binary(
    name = "si_sparrowhawk",
    srcs = ["si_sparrowhawk.sh"],
    data = [
        "//si/textnorm/classifier:tokenize_and_classify_thrax_compile_grm",
        "//si/textnorm/verbalizer:verbalize_thrax_compile_grm",
        "//utils:sh_utter",
        "sparrowhawk_configuration.ascii_proto",
        "tokenizer.ascii_proto",
        "verbalizer.ascii_proto",
    ],
)
