sh_binary(
    name = "af_sparrowhawk",
    srcs = ["af_sparrowhawk.sh"],
    data = [
        "//af/textnorm/classifier:tokenize_and_classify_thrax_compile_grm",
        "//af/textnorm/verbalizer:verbalize_thrax_compile_grm",
        "//utils:sh-utter",
        "sparrowhawk_configuration.ascii_proto",
        "tokenizer.ascii_proto",
        "verbalizer.ascii_proto",
    ],
)
